package de.chrgroth.james.app

import de.chrgroth.james.ErrorCode

enum class AppErrorCodes : ErrorCode {
    NOT_FOUND,
    APP_DISCONTINUED_NO_CHANGES_ALLOWED,

    CREATE_DEVELOPMENT_VERSION_DRAFT_EXISTS,
    UPDATE_DEVELOPMENT_VERSION_DRAFT_MISSING,
    UPDATE_DEVELOPMENT_VERSION_UPSERT_DATATYPE_NAME_BLANK,
    UPDATE_DEVELOPMENT_VERSION_UPSERT_DATATYPE_SCHEMA_NULL,
    UPDATE_DEVELOPMENT_VERSION_UPSERT_DATATYPE_SCHEMA_CONTAINS_UNKNOWN_PROPERTIES,
    UPDATE_DEVELOPMENT_VERSION_UPSERT_DATATYPE_SCHEMA_IS_NOT_OBJECT_SCHEMA,
    UPDATE_DEVELOPMENT_VERSION_UPSERT_DATATYPE_SCHEMA_INVALID,
    UPDATE_DEVELOPMENT_VERSION_REMOVE_DATATYPE_NOT_FOUND,
    UPDATE_DEVELOPMENT_VERSION_UPSERT_REPORT_NAME_BLANK,
    UPDATE_DEVELOPMENT_VERSION_REMOVE_REPORT_NOT_FOUND,

    RELEASE_DEVELOPMENT_VERSION_DRAFT_MISSING,
    RELEASE_DEVELOPMENT_VERSION_RELEASE_NOTES_BLANK,

    DELETE_STATUS_IS_NOT_DISCONTINUED;

    override val prefix = "APP"
    override val id = ordinal.toLong()
}
