# HEALTH CONFIGURATION MASKING
# -----------------------------
app.health.masked-config-keys=mongodb.connection.string,quarkus.mongodb.connection-string,app.slack.webhook-url
app.health.masked-env-keys=MONGODB_CONNECTION_STRING,SLACK_WEBHOOK_URL
