kind: pipeline
type: docker
name: build and deploy

steps:
- name: list docker services
  image: docker:dind
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  commands:
  - docker -v
  - docker stack ls

volumes:
- name: docker_socket
  host:
    path: /var/run/docker.sock