kind: pipeline
type: docker
name: build and deploy

steps:
- name: list docker services
  image: docker
  volume:
  - /var/run/docker.sock:/var/run/docker.sock
  commands:
  - echo listing docker services
  - docker -v
  - nohup dockerd &
  - docker stack ls
