# domain config
# ##### ##### #####

domain.user.defaultAdminUsername=admin
%dev.domain.user.defaultAdminPassword=admin
%test.domain.user.defaultAdminPassword=admin
%prod.domain.user.defaultAdminPassword=${quarkus.uuid}

domain.user.defaultUsers=[]
%dev.domain.user.defaultUsers[0]=user|USER
%dev.domain.user.defaultUsers[1]=dev|DEVELOPER
%test.domain.user.defaultUsers[0]=user|USER
%test.domain.user.defaultUsers[1]=dev|DEVELOPER
%prod.domain.user.defaultUsers=[]
