# domain config
# ##### ##### #####

domain.user.defaultAdminUsername=admin

%dev.domain.user.defaultAdminPassword=admin
%test.domain.user.defaultAdminPassword=admin
%prod.domain.user.defaultAdminPassword=${quarkus.uuid}
