# Templates config
# ##### ##### #####

http.index.redirect=/ui/dashboard

# Form based authentication
# ##### ##### #####

quarkus.http.auth.form.enabled=true
quarkus.http.auth.form.post-location=/auth/login
quarkus.http.auth.form.login-page=/ui/login
quarkus.http.auth.form.username-parameter=username
quarkus.http.auth.form.password-parameter=password

quarkus.http.auth.session.encryption-key=${quarkus.uuid}
%prod.quarkus.http.auth.session.encryption-key=${HTTP_AUTH_ENCRYPTION_KEY}

quarkus.http.auth.form.cookie-name=credential
quarkus.http.auth.form.http-only-cookie=true
quarkus.http.auth.form.cookie-same-site=strict
quarkus.http.auth.form.timeout=PT72H
quarkus.http.auth.form.new-cookie-interval=PT1H
quarkus.http.auth.form.cookie-max-age=PT72H

quarkus.http.auth.form.landing-page=/auth/login-redirect
quarkus.http.auth.form.error-page=/ui/login?loginError=true
