# IMPORTS
# -------
# Runs daily at 03:00 to delete import documents whose last-updated date exceeds the retention period.
app.imports.cleanup.cron=0 0 3 * * ?
# Runs every minute to trigger unattended runs for import definitions whose schedule cron expression is due.
app.imports.schedule.poll-cron=0 * * * * ?
