# https://ktor.io/docs/configuration-file.html
ktor {
  deployment {
    port = 8080
  }

  application {
    modules = [
      de.chrgroth.james.runtime.ktor.StaticContentKt.app
    ]
  }
}
