# https://ktor.io/docs/configuration-file.html
ktor {
  deployment {
    port = 8080
    # watch = [ src/main/resources ] not working for static files
  }

  application {
    modules = [
      de.chrgroth.james.runtime.ktor.StaticContentKt.app
    ]
  }
}
