#---- DATASOURCE
# using default DS from adapter-out-postgres-user

#---- FLYWAY
quarkus.flyway.app.locations=classpath:db/migration/app
quarkus.flyway.app.schemas=app_domain
# We'll handle migration programmatically to use default DS
quarkus.flyway.app.migrate-at-start=false
quarkus.flyway.app.validate-on-migrate=true
