package de.chrgroth.james.typesystem

import de.chrgroth.james.DomainErrorCode

// TODO #2 naming
internal enum class TypesystemDomainErrorCodes : DomainErrorCode {
    DATATYPE_NAME_INVALID,

    FIELD_NAME_INVALID,

    LIST_VALUE_FIELD_DEFAULT_VALUES_CONTAIN_DUPLICATES,
    LIST_VALUE_FIELD_DEFAULT_VALUES_BELOW_MIN_VALUES,
    LIST_VALUE_FIELD_DEFAULT_VALUES_ABOVE_MAX_VALUES,

    LIST_VALUE_FIELD_CONTAINS_DUPLICATES,
    LIST_VALUE_FIELD_VALUES_BELOW_MIN_VALUES,
    LIST_VALUE_FIELD_VALUES_ABOVE_MAX_VALUES,
    LIST_VALUE_FIELD_CONTAINS_NULL,

    OBJECT_DEFINITION_EMPTY_FIELDS,
    OBJECT_DEFINITION_DUPLICATE_FIELD_NAMES,

    STRING_FIELD_MIN_LENGTH_GREATER_MAX_LENGTH,

    NUMERIC_FIELD_MIN_GREATER_MAX,

    DATE_FIELD_MIN_GREATER_MAX,
    TIME_FIELD_MIN_GREATER_MAX,
    DATE_TIME_FIELD_MIN_GREATER_MAX,

    OBJECT_FIELD_DEFAULT_VALUE_NOT_SUPPORTED,
    OBJECT_FIELD_ALLOWED_VALUES_NOT_SUPPORTED,

    MANDATORY_VALUE_MISSING,
    VALUE_TYPE_MISMATCH,

    STRING_VALUE_LENGTH_BELOW_MIN,
    STRING_VALUE_LENGTH_ABOVE_MAX,
    STRING_VALUE_PATTERN_NOT_MATCHED,

    NUMERIC_VALUE_BELOW_MIN,
    NUMERIC_VALUE_ABOVE_MAX,

    DATE_VALUE_BELOW_MIN,
    DATE_VALUE_ABOVE_MAX,

    TIME_VALUE_BELOW_MIN,
    TIME_VALUE_ABOVE_MAX,

    DATE_TIME_VALUE_BELOW_MIN,
    DATE_TIME_VALUE_ABOVE_MAX,

    OBJECT_VALUE_WITHOUT_FIELD_DEFINITION,
    OBJECT_VALUE_FIELD_DEFINITION_WITHOUT_VALUE;

    override val prefix = "TYPESYSTEM"
    override val id = ordinal.toLong()
}
