#---- DATASOURCE ---
quarkus.datasource.db-kind=postgresql

quarkus.datasource.username=james
quarkus.datasource.password=james

%prod.quarkus.datasource.jdbc.url=${DB_POSTGRES_URL}
%prod.quarkus.datasource.username=${DB_POSTGRES_USERNAME}
%prod.quarkus.datasource.password=${DB_POSTGRES_PASSWORD}

quarkus.datasource.metrics.enabled=true
