#---- DATASOURCE
quarkus.datasource.users.db-kind=postgresql

quarkus.datasource.users.username=james
quarkus.datasource.users.password=james

%prod.quarkus.datasource.users.jdbc.url=${DB_POSTGRES_URL}
%prod.quarkus.datasource.users.username=${DB_POSTGRES_USERNAME}
%prod.quarkus.datasource.users.password=${DB_POSTGRES_PASSWORD}

quarkus.datasource.users.metrics.enabled=true

#---- FLYWAY
quarkus.flyway.users.locations=classpath:db/migration/user
quarkus.flyway.users.schemas=user_domain
quarkus.flyway.users.out-of-order=false
quarkus.flyway.users.migrate-at-start=true
quarkus.flyway.users.validate-on-migrate=true

#---- jOOQ
quarkus.jooq.migrate=false
quarkus.jooq.dialect=POSTGRES
quarkus.jooq.datasource=users
quarkus.jooq.sql-dialect=POSTGRES
