#---- DATASOURCE
quarkus.datasource.db-kind=postgresql
quarkus.datasource.password=jamesplatform
quarkus.datasource.username=jamesplatform

quarkus.datasource.metrics.enabled=true

quarkus.datasource.devservices.enabled=true
quarkus.datasource.devservices.show-logs=true
quarkus.datasource.devservices.reuse=false

%prod.quarkus.datasource.jdbc.url=${DB_POSTGRES_URL}
%prod.quarkus.datasource.username=${DB_POSTGRES_USERNAME}
%prod.quarkus.datasource.password=${DB_POSTGRES_PASSWORD}

#---- HIBERNATE
quarkus.hibernate-orm.metrics.enabled=true
quarkus.hibernate-orm.packages=de.chrgroth.james.platform.adapter.out.postgres.user

#---- FLYWAY
quarkus.flyway.locations=classpath:db/migration/user
quarkus.flyway.schemas=user_domain
quarkus.flyway.migrate-at-start=true
quarkus.flyway.validate-on-migrate=true
