package de.chrgroth.james.platform.domain.error

sealed interface DomainError {
  val code: String
}

enum class LoginError(override val code: String) : DomainError {
  INVALID_CREDENTIALS("LOGIN-001"),
  ;
}

enum class TokenError(override val code: String) : DomainError {
  ENCRYPTION_FAILED("TOKEN-001"),
  DECRYPTION_FAILED("TOKEN-002"),
  INVALID_FORMAT("TOKEN-003"),
  ;
}

enum class UserProfileError(override val code: String) : DomainError {
  USER_NOT_FOUND("PROFILE-001"),
  USERNAME_ALREADY_EXISTS("PROFILE-002"),
  INVALID_CURRENT_PASSWORD("PROFILE-003"),
  BLANK_INPUT("PROFILE-004"),
  PASSWORDS_DO_NOT_MATCH("PROFILE-005"),
  ;
}

enum class UserAdminError(override val code: String) : DomainError {
  USER_NOT_FOUND("ADMIN-001"),
  USERNAME_ALREADY_EXISTS("ADMIN-002"),
  BLANK_INPUT("ADMIN-003"),
  CANNOT_DEACTIVATE_SELF("ADMIN-004"),
  CANNOT_DELETE_SELF("ADMIN-005"),
  PASSWORDS_DO_NOT_MATCH("ADMIN-006"),
  CANNOT_REMOVE_OWN_ADMIN_ROLE("ADMIN-007"),
  SINGLE_ADMIN_VIOLATION("ADMIN-008"),
  ;
}

enum class AppError(override val code: String) : DomainError {
  APP_NOT_FOUND("APP-001"),
  APP_NAME_ALREADY_EXISTS("APP-002"),
  BLANK_INPUT("APP-003"),
  ALREADY_INACTIVE("APP-004"),
  ;
}

enum class AppVersionError(override val code: String) : DomainError {
  APP_NOT_FOUND("APPVER-001"),
  VERSION_NOT_FOUND("APPVER-002"),
  VERSION_NUMBER_ALREADY_EXISTS("APPVER-003"),
  BLANK_INPUT("APPVER-004"),
  INVALID_VERSION_NUMBER_FORMAT("APPVER-005"),
  VERSION_NOT_IN_DRAFT("APPVER-006"),
  DRAFT_VERSION_ALREADY_EXISTS("APPVER-007"),
  ENTITY_NOT_FOUND("APPVER-008"),
  ENTITY_NAME_ALREADY_EXISTS("APPVER-009"),
  PROPERTY_NOT_FOUND("APPVER-010"),
  PROPERTY_NAME_ALREADY_EXISTS("APPVER-011"),
  REPORT_NOT_FOUND("APPVER-012"),
  REPORT_NAME_ALREADY_EXISTS("APPVER-013"),
  INVALID_PROPERTY_TYPE("APPVER-015"),
  INVALID_BUMP_TYPE("APPVER-016"),
  ;
}

enum class UserAppStoreError(override val code: String) : DomainError {
  APP_NOT_FOUND("STORE-001"),
  NO_PUBLISHED_VERSION("STORE-002"),
  ALREADY_INSTALLED("STORE-003"),
  NOT_INSTALLED("STORE-004"),
  INSTALLED_APP_NOT_FOUND("STORE-005"),
  ALREADY_UP_TO_DATE("STORE-006"),
  ;
}

enum class PropertyConstraintViolation(override val code: String) : DomainError {
  UNIQUE_KEY_VIOLATION("PROP-002"),
  MIN_VALUE_VIOLATION("PROP-003"),
  MAX_VALUE_VIOLATION("PROP-004"),
  MIN_LENGTH_VIOLATION("PROP-005"),
  MAX_LENGTH_VIOLATION("PROP-006"),
  PATTERN_VIOLATION("PROP-007"),
  MIN_SIZE_VIOLATION("PROP-008"),
  MAX_SIZE_VIOLATION("PROP-009"),
  ;
}
