name: Remove old artifacts

on:
  schedule:
    # Every day at 1am
    - cron: '0 1 * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      actions: write
      packages: write
    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1.4.0
        with:
          age: '14 days'
          skip-recent: 3
      - name: Remove old packages
        uses: smartsquaregmbh/delete-old-packages@v0.8.1
        with:
          organization: my-organization
          type: docker
          keep: 3
