package de.chrgroth.james.app

import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_NAME_BLANK
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_NAME_DUPLICATE
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_NAME_INVALID
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_NOT_FOUND
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_ADDITIONAL_PROPERTIES_NOT_SUPPORTED
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_ANNOTATIONS_DEFAULT_ONLY_SUPPORTED_BOOLEAN_NUMBER_STRING
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_ANNOTATIONS_READ_ONLY_NOT_SUPPORTED
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_ANNOTATIONS_TITLE_MANDATORY_FOR_TOP_LEVEL_NOT_SUPPORTED_FOR_EVERYTHING_ELSE
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_ANNOTATIONS_WRITE_ONLY_NOT_SUPPORTED
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_CONTAINS_INVALID_TYPE
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_CONTAINS_NO_TYPES
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_DEFINES_CONTAINS
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_LIST_MODE_DEFINES_ADDITIONAL_ITEMS
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_LIST_OR_TUPLE_MODE_UNDEFINED
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_MAX_ITEMS_SMALLER_MIN_ITEMS
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_NEGATIVE_MIN_ITEMS
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_NEGATIVE_OR_ZERO_MAX_ITEMS
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_TUPLE_MODE_DEFINES_ADDITIONAL_ITEMS
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_TUPLE_MODE_DEFINES_MAX_ITEMS
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_TUPLE_MODE_DEFINES_MIN_ITEMS
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_COMBINED_PROPERTY_ONLY_SUPPORTS_ENUM_USECASE_FOR_STRING_AND_NUMBER
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_COMBINED_PROPERTY_UNSUPPORTED_CRITERION
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_CONTAINS_UNPROCESSED_PROPERTIES
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_CONTENT_BLANK
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_ENUM_PROPERTY_NOT_SUPPORTED
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_ENUM_PROPERTY_VALUES_MISMATCHING_TYPE
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_ENUM_PROPERTY_VALUES_MISSING
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_INVALID
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_IS_NOT_OBJECT_SCHEMA
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_MAX_PROPERTIES_NOT_SUPPORTED
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_MIN_PROPERTIES_NOT_SUPPORTED
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_NULL
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_NUMBER_PROPERTY_MAX_AND_EXCLUSIVE_MAX_LIMIT
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_NUMBER_PROPERTY_MAX_LIMIT_SMALLER_MIN_LIMIT
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_NUMBER_PROPERTY_MIN_AND_EXCLUSIVE_MIN_LIMIT
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_NUMBER_PROPERTY_MULTIPLE_OF_FLOATING_POINT_FOR_INTEGER
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_NUMBER_PROPERTY_MULTIPLE_OF_NEGATIVE_OR_ZERO
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_PATTERN_PROPERTIES_NOT_SUPPORTED
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_PROPERTIES_INVALID_TYPE
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_PROPERTY_DEPENDENCIES_NOT_SUPPORTED
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_PROPERTY_NAME_SCHEMA_NOT_SUPPORTED
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_REQUIRED_PROPERTIES_DO_NOT_EXIST
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_SCHEMA_DEPENDENCIES_NOT_SUPPORTED
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_STRING_PROPERTY_MAX_LENGTH_SMALLER_MIN_LENGTH
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_STRING_PROPERTY_NEGATIVE_MIN_LENGTH
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_STRING_PROPERTY_NEGATIVE_OR_ZERO_MAX_LENGTH
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_SCHEMA_STRING_PROPERTY_UNSUPPORTED_FORMAT
import de.chrgroth.james.app.AppErrorCodes.APP_DATATYPE_VERSION_NEGATIVE
import de.chrgroth.james.app.AppErrorCodes.APP_DISCONTINUED_NO_CHANGES_ALLOWED
import de.chrgroth.james.app.AppErrorCodes.APP_NAME_BLANK
import de.chrgroth.james.app.AppErrorCodes.APP_REPORT_NAME_BLANK
import de.chrgroth.james.app.AppErrorCodes.APP_REPORT_NAME_DUPLICATE
import de.chrgroth.james.app.AppErrorCodes.APP_REPORT_NOT_FOUND
import de.chrgroth.james.app.AppErrorCodes.APP_VERSION_NOT_FOUND
import de.chrgroth.james.app.AppErrorCodes.APP_VERSION_RELEASE_NOTE_BLANK
import de.chrgroth.james.app.AppErrorCodes.CREATE_DEVELOPMENT_VERSION_DRAFT_EXISTS
import de.chrgroth.james.app.AppErrorCodes.DELETE_STATUS_IS_NOT_DISCONTINUED
import de.chrgroth.james.app.AppErrorCodes.RELEASE_DEVELOPMENT_VERSION_DRAFT_MISSING
import de.chrgroth.james.app.AppErrorCodes.UPDATE_DEVELOPMENT_VERSION_DRAFT_MISSING
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class AppErrorCodesTests {

    @Test
    fun ensureErrorCodesNotChanged() {
        assertThat(APP_NAME_BLANK.toGlobalRepresentation()).isEqualTo("APP_000_APP_NAME_BLANK")
        assertThat(APP_DATATYPE_NOT_FOUND.toGlobalRepresentation()).isEqualTo("APP_001_APP_DATATYPE_NOT_FOUND")
        assertThat(APP_DATATYPE_NAME_BLANK.toGlobalRepresentation()).isEqualTo("APP_002_APP_DATATYPE_NAME_BLANK")
        assertThat(APP_DATATYPE_NAME_INVALID.toGlobalRepresentation()).isEqualTo("APP_003_APP_DATATYPE_NAME_INVALID")
        assertThat(APP_DATATYPE_NAME_DUPLICATE.toGlobalRepresentation()).isEqualTo("APP_004_APP_DATATYPE_NAME_DUPLICATE")
        assertThat(APP_DATATYPE_VERSION_NEGATIVE.toGlobalRepresentation()).isEqualTo("APP_005_APP_DATATYPE_VERSION_NEGATIVE")
        assertThat(APP_DATATYPE_SCHEMA_CONTENT_BLANK.toGlobalRepresentation()).isEqualTo("APP_006_APP_DATATYPE_SCHEMA_CONTENT_BLANK")
        assertThat(APP_DATATYPE_SCHEMA_NULL.toGlobalRepresentation()).isEqualTo("APP_007_APP_DATATYPE_SCHEMA_NULL")
        assertThat(APP_DATATYPE_SCHEMA_CONTAINS_UNPROCESSED_PROPERTIES.toGlobalRepresentation()).isEqualTo("APP_008_APP_DATATYPE_SCHEMA_CONTAINS_UNPROCESSED_PROPERTIES")
        assertThat(APP_DATATYPE_SCHEMA_IS_NOT_OBJECT_SCHEMA.toGlobalRepresentation()).isEqualTo("APP_009_APP_DATATYPE_SCHEMA_IS_NOT_OBJECT_SCHEMA")
        assertThat(APP_DATATYPE_SCHEMA_INVALID.toGlobalRepresentation()).isEqualTo("APP_010_APP_DATATYPE_SCHEMA_INVALID")
        assertThat(APP_DATATYPE_SCHEMA_MIN_PROPERTIES_NOT_SUPPORTED.toGlobalRepresentation()).isEqualTo("APP_011_APP_DATATYPE_SCHEMA_MIN_PROPERTIES_NOT_SUPPORTED")
        assertThat(APP_DATATYPE_SCHEMA_MAX_PROPERTIES_NOT_SUPPORTED.toGlobalRepresentation()).isEqualTo("APP_012_APP_DATATYPE_SCHEMA_MAX_PROPERTIES_NOT_SUPPORTED")
        assertThat(APP_DATATYPE_SCHEMA_ADDITIONAL_PROPERTIES_NOT_SUPPORTED.toGlobalRepresentation()).isEqualTo("APP_013_APP_DATATYPE_SCHEMA_ADDITIONAL_PROPERTIES_NOT_SUPPORTED")
        assertThat(APP_DATATYPE_SCHEMA_PATTERN_PROPERTIES_NOT_SUPPORTED.toGlobalRepresentation()).isEqualTo("APP_014_APP_DATATYPE_SCHEMA_PATTERN_PROPERTIES_NOT_SUPPORTED")
        assertThat(APP_DATATYPE_SCHEMA_PROPERTY_NAME_SCHEMA_NOT_SUPPORTED.toGlobalRepresentation()).isEqualTo("APP_015_APP_DATATYPE_SCHEMA_PROPERTY_NAME_SCHEMA_NOT_SUPPORTED")
        assertThat(APP_DATATYPE_SCHEMA_PROPERTY_DEPENDENCIES_NOT_SUPPORTED.toGlobalRepresentation()).isEqualTo("APP_016_APP_DATATYPE_SCHEMA_PROPERTY_DEPENDENCIES_NOT_SUPPORTED")
        assertThat(APP_DATATYPE_SCHEMA_SCHEMA_DEPENDENCIES_NOT_SUPPORTED.toGlobalRepresentation()).isEqualTo("APP_017_APP_DATATYPE_SCHEMA_SCHEMA_DEPENDENCIES_NOT_SUPPORTED")
        assertThat(APP_DATATYPE_SCHEMA_PROPERTIES_INVALID_TYPE.toGlobalRepresentation()).isEqualTo("APP_018_APP_DATATYPE_SCHEMA_PROPERTIES_INVALID_TYPE")
        assertThat(APP_DATATYPE_SCHEMA_REQUIRED_PROPERTIES_DO_NOT_EXIST.toGlobalRepresentation()).isEqualTo("APP_019_APP_DATATYPE_SCHEMA_REQUIRED_PROPERTIES_DO_NOT_EXIST")
        assertThat(APP_DATATYPE_SCHEMA_STRING_PROPERTY_NEGATIVE_MIN_LENGTH.toGlobalRepresentation()).isEqualTo("APP_020_APP_DATATYPE_SCHEMA_STRING_PROPERTY_NEGATIVE_MIN_LENGTH")
        assertThat(APP_DATATYPE_SCHEMA_STRING_PROPERTY_NEGATIVE_OR_ZERO_MAX_LENGTH.toGlobalRepresentation()).isEqualTo("APP_021_APP_DATATYPE_SCHEMA_STRING_PROPERTY_NEGATIVE_OR_ZERO_MAX_LENGTH")
        assertThat(APP_DATATYPE_SCHEMA_STRING_PROPERTY_MAX_LENGTH_SMALLER_MIN_LENGTH.toGlobalRepresentation()).isEqualTo("APP_022_APP_DATATYPE_SCHEMA_STRING_PROPERTY_MAX_LENGTH_SMALLER_MIN_LENGTH")
        assertThat(APP_DATATYPE_SCHEMA_STRING_PROPERTY_UNSUPPORTED_FORMAT.toGlobalRepresentation()).isEqualTo("APP_023_APP_DATATYPE_SCHEMA_STRING_PROPERTY_UNSUPPORTED_FORMAT")
        assertThat(APP_DATATYPE_SCHEMA_NUMBER_PROPERTY_MIN_AND_EXCLUSIVE_MIN_LIMIT.toGlobalRepresentation()).isEqualTo("APP_024_APP_DATATYPE_SCHEMA_NUMBER_PROPERTY_MIN_AND_EXCLUSIVE_MIN_LIMIT")
        assertThat(APP_DATATYPE_SCHEMA_NUMBER_PROPERTY_MAX_AND_EXCLUSIVE_MAX_LIMIT.toGlobalRepresentation()).isEqualTo("APP_025_APP_DATATYPE_SCHEMA_NUMBER_PROPERTY_MAX_AND_EXCLUSIVE_MAX_LIMIT")
        assertThat(APP_DATATYPE_SCHEMA_NUMBER_PROPERTY_MAX_LIMIT_SMALLER_MIN_LIMIT.toGlobalRepresentation()).isEqualTo("APP_026_APP_DATATYPE_SCHEMA_NUMBER_PROPERTY_MAX_LIMIT_SMALLER_MIN_LIMIT")
        assertThat(APP_DATATYPE_SCHEMA_NUMBER_PROPERTY_MULTIPLE_OF_NEGATIVE_OR_ZERO.toGlobalRepresentation()).isEqualTo("APP_027_APP_DATATYPE_SCHEMA_NUMBER_PROPERTY_MULTIPLE_OF_NEGATIVE_OR_ZERO")
        assertThat(APP_DATATYPE_SCHEMA_NUMBER_PROPERTY_MULTIPLE_OF_FLOATING_POINT_FOR_INTEGER.toGlobalRepresentation()).isEqualTo("APP_028_APP_DATATYPE_SCHEMA_NUMBER_PROPERTY_MULTIPLE_OF_FLOATING_POINT_FOR_INTEGER")
        assertThat(APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_LIST_OR_TUPLE_MODE_UNDEFINED.toGlobalRepresentation()).isEqualTo("APP_029_APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_LIST_OR_TUPLE_MODE_UNDEFINED")
        assertThat(APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_LIST_MODE_DEFINES_ADDITIONAL_ITEMS.toGlobalRepresentation()).isEqualTo("APP_030_APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_LIST_MODE_DEFINES_ADDITIONAL_ITEMS")
        assertThat(APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_TUPLE_MODE_DEFINES_ADDITIONAL_ITEMS.toGlobalRepresentation()).isEqualTo("APP_031_APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_TUPLE_MODE_DEFINES_ADDITIONAL_ITEMS")
        assertThat(APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_NEGATIVE_MIN_ITEMS.toGlobalRepresentation()).isEqualTo("APP_032_APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_NEGATIVE_MIN_ITEMS")
        assertThat(APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_NEGATIVE_OR_ZERO_MAX_ITEMS.toGlobalRepresentation()).isEqualTo("APP_033_APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_NEGATIVE_OR_ZERO_MAX_ITEMS")
        assertThat(APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_MAX_ITEMS_SMALLER_MIN_ITEMS.toGlobalRepresentation()).isEqualTo("APP_034_APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_MAX_ITEMS_SMALLER_MIN_ITEMS")
        assertThat(APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_TUPLE_MODE_DEFINES_MIN_ITEMS.toGlobalRepresentation()).isEqualTo("APP_035_APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_TUPLE_MODE_DEFINES_MIN_ITEMS")
        assertThat(APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_TUPLE_MODE_DEFINES_MAX_ITEMS.toGlobalRepresentation()).isEqualTo("APP_036_APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_TUPLE_MODE_DEFINES_MAX_ITEMS")
        assertThat(APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_DEFINES_CONTAINS.toGlobalRepresentation()).isEqualTo("APP_037_APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_DEFINES_CONTAINS")
        assertThat(APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_CONTAINS_NO_TYPES.toGlobalRepresentation()).isEqualTo("APP_038_APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_CONTAINS_NO_TYPES")
        assertThat(APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_CONTAINS_INVALID_TYPE.toGlobalRepresentation()).isEqualTo("APP_039_APP_DATATYPE_SCHEMA_ARRAY_PROPERTY_CONTAINS_INVALID_TYPE")
        assertThat(APP_DATATYPE_SCHEMA_COMBINED_PROPERTY_UNSUPPORTED_CRITERION.toGlobalRepresentation()).isEqualTo("APP_040_APP_DATATYPE_SCHEMA_COMBINED_PROPERTY_UNSUPPORTED_CRITERION")
        assertThat(APP_DATATYPE_SCHEMA_COMBINED_PROPERTY_ONLY_SUPPORTS_ENUM_USECASE_FOR_STRING_AND_NUMBER.toGlobalRepresentation()).isEqualTo("APP_041_APP_DATATYPE_SCHEMA_COMBINED_PROPERTY_ONLY_SUPPORTS_ENUM_USECASE_FOR_STRING_AND_NUMBER")
        assertThat(APP_DATATYPE_SCHEMA_ENUM_PROPERTY_NOT_SUPPORTED.toGlobalRepresentation()).isEqualTo("APP_042_APP_DATATYPE_SCHEMA_ENUM_PROPERTY_NOT_SUPPORTED")
        assertThat(APP_DATATYPE_SCHEMA_ENUM_PROPERTY_VALUES_MISSING.toGlobalRepresentation()).isEqualTo("APP_043_APP_DATATYPE_SCHEMA_ENUM_PROPERTY_VALUES_MISSING")
        assertThat(APP_DATATYPE_SCHEMA_ENUM_PROPERTY_VALUES_MISMATCHING_TYPE.toGlobalRepresentation()).isEqualTo("APP_044_APP_DATATYPE_SCHEMA_ENUM_PROPERTY_VALUES_MISMATCHING_TYPE")
        assertThat(APP_DATATYPE_SCHEMA_ANNOTATIONS_TITLE_MANDATORY_FOR_TOP_LEVEL_NOT_SUPPORTED_FOR_EVERYTHING_ELSE.toGlobalRepresentation()).isEqualTo("APP_045_APP_DATATYPE_SCHEMA_ANNOTATIONS_TITLE_MANDATORY_FOR_TOP_LEVEL_NOT_SUPPORTED_FOR_EVERYTHING_ELSE")
        assertThat(APP_DATATYPE_SCHEMA_ANNOTATIONS_DEFAULT_ONLY_SUPPORTED_BOOLEAN_NUMBER_STRING.toGlobalRepresentation()).isEqualTo("APP_046_APP_DATATYPE_SCHEMA_ANNOTATIONS_DEFAULT_ONLY_SUPPORTED_BOOLEAN_NUMBER_STRING")
        assertThat(APP_DATATYPE_SCHEMA_ANNOTATIONS_READ_ONLY_NOT_SUPPORTED.toGlobalRepresentation()).isEqualTo("APP_047_APP_DATATYPE_SCHEMA_ANNOTATIONS_READ_ONLY_NOT_SUPPORTED")
        assertThat(APP_DATATYPE_SCHEMA_ANNOTATIONS_WRITE_ONLY_NOT_SUPPORTED.toGlobalRepresentation()).isEqualTo("APP_048_APP_DATATYPE_SCHEMA_ANNOTATIONS_WRITE_ONLY_NOT_SUPPORTED")
        assertThat(APP_REPORT_NOT_FOUND.toGlobalRepresentation()).isEqualTo("APP_049_APP_REPORT_NOT_FOUND")
        assertThat(APP_REPORT_NAME_BLANK.toGlobalRepresentation()).isEqualTo("APP_050_APP_REPORT_NAME_BLANK")
        assertThat(APP_REPORT_NAME_DUPLICATE.toGlobalRepresentation()).isEqualTo("APP_051_APP_REPORT_NAME_DUPLICATE")
        assertThat(APP_VERSION_NOT_FOUND.toGlobalRepresentation()).isEqualTo("APP_052_APP_VERSION_NOT_FOUND")
        assertThat(APP_VERSION_RELEASE_NOTE_BLANK.toGlobalRepresentation()).isEqualTo("APP_053_APP_VERSION_RELEASE_NOTE_BLANK")
        assertThat(APP_DISCONTINUED_NO_CHANGES_ALLOWED.toGlobalRepresentation()).isEqualTo("APP_054_APP_DISCONTINUED_NO_CHANGES_ALLOWED")
        assertThat(CREATE_DEVELOPMENT_VERSION_DRAFT_EXISTS.toGlobalRepresentation()).isEqualTo("APP_055_CREATE_DEVELOPMENT_VERSION_DRAFT_EXISTS")
        assertThat(UPDATE_DEVELOPMENT_VERSION_DRAFT_MISSING.toGlobalRepresentation()).isEqualTo("APP_056_UPDATE_DEVELOPMENT_VERSION_DRAFT_MISSING")
        assertThat(RELEASE_DEVELOPMENT_VERSION_DRAFT_MISSING.toGlobalRepresentation()).isEqualTo("APP_057_RELEASE_DEVELOPMENT_VERSION_DRAFT_MISSING")
        assertThat(DELETE_STATUS_IS_NOT_DISCONTINUED.toGlobalRepresentation()).isEqualTo("APP_058_DELETE_STATUS_IS_NOT_DISCONTINUED")
    }

    @Test
    fun ensureNumberOfErrorCodesNotChanged() {
        assertThat(AppErrorCodes.values()).hasSize(59)
    }
}
